import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/header/header";
import Footer from "@/components/footer/footer";
import QueryClientProviderComponent from "@/providers/QueryClientProviderComponent";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <QueryClientProviderComponent>
      <html lang="en">
        <body>
          <div className="min-h-screen flex flex-col justify-between">
            <div>
              <Header />
              {children}
            </div>
            <Footer />
          </div>
        </body>
      </html>
    </QueryClientProviderComponent>
  );
}
